export enum OrderStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  DISAPPROVED = 'DISAPPROVED',
  CANCELED = 'CANCELED',

  // TODO: move to a payment Aggregate
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_APPROVED = 'PAYMENT_APPROVED',
  PAYMENT_ERROR = 'PAYMENT_ERROR',

  // TODO: move to a delivery Aggregate
  DELIVERY_PENDING = 'DELIVERY_PENDING',
  DELIVERY_IN_PROGRESS = 'DELIVERY_IN_PROGRESS',
  DELIVERY_IN_ROUTE = 'DELIVERY_IN_ROUTE',
  DELIVERED = 'DELIVERED',
  DELIVERY_ERROR = 'DELIVERY_ERROR',
}
