version: '3'

services:

  node-api:
    container_name: node-api
    build: .
    restart: always
    working_dir: /usr/src/app
    entrypoint: /usr/src/app/.docker/entrypoint.sh
    depends_on:
      - postgres-database
      - keycloak-auth
    ports:
      - '3000:3000'
      - '9222:9222'
    volumes:
      - ./:/usr/src/app/
    networks:
      - application-network

  postgres-database:
    container_name: postgres-database
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - application-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=application,keycloak

  keycloak-auth:
    container_name: keycloak-auth
    image: jboss/keycloak:16.1.0
    depends_on:
      - postgres-database
    ports:
      - 8080:8080
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    networks:
      - application-network
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_PORT=5432
      - DB_ADDR=postgres-database
      - DB_SCHEMA=public
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - DB_PASSWORD=postgres

networks:
  application-network:
    driver: bridge

volumes:
  database-data:
  keycloak-data:
